#!/usr/bin/env node
/**
 * Backend scaffold — creates all src/** files.
 * Skips root files (package.json, tsconfig, nest-cli, .env, .gitignore, prisma/).
 *
 * Run from backend/: node scripts/scaffold-backend.js
 */
import fs from "node:fs";
import path from "node:path";

const SRC = path.join(process.cwd(), "src");
const counters = { created: 0, skipped: 0 };

function write(rel, lines) {
  const full = path.join(SRC, rel);
  if (fs.existsSync(full)) {
    counters.skipped++;
    console.log(`  \x1b[33m•\x1b[0m src/${rel}  (exists)`);
    return;
  }
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, lines.join("\n") + "\n");
  counters.created++;
  console.log(`  \x1b[32m+\x1b[0m src/${rel}`);
}

const J = (o) => JSON.stringify(o, null, 2);

// ─────────────────────────────────────────────────────────────────────────────
// CONFIG
// ─────────────────────────────────────────────────────────────────────────────

write("config/env.ts", [
  'import { z } from "zod";',
  '',
  'const EnvSchema = z.object({',
  '  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),',
  '  PORT: z.coerce.number().default(4000),',
  '  FRONTEND_URL: z.string().default("http://localhost:3000"),',
  '  DATABASE_URL: z.string().min(1),',
  '  REDIS_URL: z.string().min(1),',
  '  JWT_ACCESS_SECRET: z.string().min(32),',
  '  JWT_REFRESH_SECRET: z.string().min(32),',
  '  JWT_ACCESS_TTL: z.string().default("15m"),',
  '  JWT_REFRESH_TTL: z.string().default("30d"),',
  '  COOKIE_DOMAIN: z.string().default("localhost"),',
  '  COOKIE_SECURE: z.coerce.boolean().default(false),',
  '  COOKIE_SAMESITE: z.enum(["lax", "strict", "none"]).default("lax"),',
  '  EMAIL_FROM: z.string().default("noreply@meridian.test"),',
  '  RESEND_API_KEY: z.string().optional(),',
  '});',
  '',
  'export type Env = z.infer<typeof EnvSchema>;',
  '',
  'let cached: Env | null = null;',
  '',
  'export function getEnv(): Env {',
  '  if (cached) return cached;',
  '  const parsed = EnvSchema.safeParse(process.env);',
  '  if (!parsed.success) {',
  '    console.error("Invalid environment variables:");',
  '    console.error(parsed.error.flatten().fieldErrors);',
  '    process.exit(1);',
  '  }',
  '  cached = parsed.data;',
  '  return cached;',
  '}',
]);

write("config/config.module.ts", [
  'import { Global, Module } from "@nestjs/common";',
  'import { ConfigModule as NestConfigModule } from "@nestjs/config";',
  'import { getEnv } from "./env";',
  '',
  '@Global()',
  '@Module({',
  '  imports: [',
  '    NestConfigModule.forRoot({',
  '      isGlobal: true,',
  '      validate: () => getEnv(),',
  '      envFilePath: [".env.local", ".env"],',
  '    }),',
  '  ],',
  '})',
  'export class ConfigModule {}',
]);

write("config/index.ts", [
  'export * from "./env";',
  'export * from "./config.module";',
]);

// ─────────────────────────────────────────────────────────────────────────────
// COMMON
// ─────────────────────────────────────────────────────────────────────────────

write("common/filters/http-exception.filter.ts", [
  'import {',
  '  ArgumentsHost,',
  '  Catch,',
  '  ExceptionFilter,',
  '  HttpException,',
  '  HttpStatus,',
  '  Logger,',
  '} from "@nestjs/common";',
  'import type { FastifyReply } from "fastify";',
  '',
  '@Catch()',
  'export class HttpExceptionFilter implements ExceptionFilter {',
  '  private readonly logger = new Logger(HttpExceptionFilter.name);',
  '',
  '  catch(exception: unknown, host: ArgumentsHost) {',
  '    const reply = host.switchToHttp().getResponse<FastifyReply>();',
  '    if (exception instanceof HttpException) {',
  '      const status = exception.getStatus();',
  '      const body = exception.getResponse();',
  '      const payload = typeof body === "string" ? { message: body } : (body as object);',
  '      reply.status(status).send({ error: true, ...payload });',
  '      return;',
  '    }',
  '    this.logger.error(exception);',
  '    reply.status(HttpStatus.INTERNAL_SERVER_ERROR).send({',
  '      error: true,',
  '      message: "Internal server error",',
  '    });',
  '  }',
  '}',
]);

write("common/interceptors/response.interceptor.ts", [
  'import {',
  '  CallHandler,',
  '  ExecutionContext,',
  '  Injectable,',
  '  NestInterceptor,',
  '} from "@nestjs/common";',
  'import { map, type Observable } from "rxjs";',
  '',
  'export interface ApiResponse<T> { data: T; }',
  '',
  '@Injectable()',
  'export class ResponseInterceptor<T> implements NestInterceptor<T, ApiResponse<T>> {',
  '  intercept(_ctx: ExecutionContext, next: CallHandler<T>): Observable<ApiResponse<T>> {',
  '    return next.handle().pipe(map((data) => ({ data })));',
  '  }',
  '}',
]);

write("common/pipes/zod-validation.pipe.ts", [
  'import {',
  '  ArgumentMetadata,',
  '  BadRequestException,',
  '  Injectable,',
  '  PipeTransform,',
  '} from "@nestjs/common";',
  'import type { ZodSchema } from "zod";',
  '',
  '@Injectable()',
  'export class ZodValidationPipe implements PipeTransform {',
  '  constructor(private readonly schema: ZodSchema) {}',
  '',
  '  transform(value: unknown, _meta: ArgumentMetadata) {',
  '    const result = this.schema.safeParse(value);',
  '    if (!result.success) {',
  '      throw new BadRequestException({',
  '        message: "Validation failed",',
  '        issues: result.error.flatten().fieldErrors,',
  '      });',
  '    }',
  '    return result.data;',
  '  }',
  '}',
]);

write("common/decorators/current-user.decorator.ts", [
  'import { createParamDecorator, ExecutionContext } from "@nestjs/common";',
  '',
  'export interface AuthUser {',
  '  id: string;',
  '  email: string;',
  '  role: string;',
  '}',
  '',
  'export const CurrentUser = createParamDecorator(',
  '  (_data: unknown, ctx: ExecutionContext): AuthUser | null => {',
  '    const req = ctx.switchToHttp().getRequest<{ user?: AuthUser }>();',
  '    return req.user ?? null;',
  '  },',
  ');',
]);

write("common/guards/jwt.guard.ts", [
  'import {',
  '  CanActivate,',
  '  ExecutionContext,',
  '  Injectable,',
  '  UnauthorizedException,',
  '} from "@nestjs/common";',
  'import { JwtService } from "@nestjs/jwt";',
  'import type { FastifyRequest } from "fastify";',
  '',
  '@Injectable()',
  'export class JwtGuard implements CanActivate {',
  '  constructor(private readonly jwt: JwtService) {}',
  '',
  '  async canActivate(ctx: ExecutionContext): Promise<boolean> {',
  '    const req = ctx.switchToHttp().getRequest<FastifyRequest>();',
  '    const header = req.headers.authorization;',
  '    if (!header?.startsWith("Bearer ")) throw new UnauthorizedException();',
  '    try {',
  '      const payload = await this.jwt.verifyAsync(header.slice(7));',
  '      (req as FastifyRequest & { user: unknown }).user = {',
  '        id: payload.sub,',
  '        email: payload.email,',
  '        role: payload.role,',
  '      };',
  '      return true;',
  '    } catch {',
  '      throw new UnauthorizedException();',
  '    }',
  '  }',
  '}',
]);

write("common/guards/optional-jwt.guard.ts", [
  'import { CanActivate, ExecutionContext, Injectable } from "@nestjs/common";',
  'import { JwtService } from "@nestjs/jwt";',
  'import type { FastifyRequest } from "fastify";',
  '',
  '@Injectable()',
  'export class OptionalJwtGuard implements CanActivate {',
  '  constructor(private readonly jwt: JwtService) {}',
  '',
  '  async canActivate(ctx: ExecutionContext): Promise<boolean> {',
  '    const req = ctx.switchToHttp().getRequest<FastifyRequest>();',
  '    const header = req.headers.authorization;',
  '    if (!header?.startsWith("Bearer ")) return true;',
  '    try {',
  '      const payload = await this.jwt.verifyAsync(header.slice(7));',
  '      (req as FastifyRequest & { user: unknown }).user = {',
  '        id: payload.sub,',
  '        email: payload.email,',
  '        role: payload.role,',
  '      };',
  '    } catch { /* ignore */ }',
  '    return true;',
  '  }',
  '}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// INFRA
// ─────────────────────────────────────────────────────────────────────────────

write("infra/database/prisma.service.ts", [
  'import { Injectable, OnModuleDestroy, OnModuleInit, Logger } from "@nestjs/common";',
  'import { PrismaClient } from "@prisma/client";',
  '',
  '@Injectable()',
  'export class PrismaService extends PrismaClient implements OnModuleInit, OnModuleDestroy {',
  '  private readonly logger = new Logger(PrismaService.name);',
  '',
  '  async onModuleInit() {',
  '    await this.$connect();',
  '    this.logger.log("Prisma connected");',
  '  }',
  '',
  '  async onModuleDestroy() {',
  '    await this.$disconnect();',
  '  }',
  '}',
]);

write("infra/database/database.module.ts", [
  'import { Global, Module } from "@nestjs/common";',
  'import { PrismaService } from "./prisma.service";',
  '',
  '@Global()',
  '@Module({',
  '  providers: [PrismaService],',
  '  exports: [PrismaService],',
  '})',
  'export class DatabaseModule {}',
]);

write("infra/cache/redis.service.ts", [
  'import { Injectable, OnModuleDestroy, OnModuleInit, Logger } from "@nestjs/common";',
  'import Redis from "ioredis";',
  'import { getEnv } from "@/config/env";',
  '',
  '@Injectable()',
  'export class RedisService implements OnModuleInit, OnModuleDestroy {',
  '  private readonly logger = new Logger(RedisService.name);',
  '  readonly client: Redis;',
  '',
  '  constructor() {',
  '    this.client = new Redis(getEnv().REDIS_URL, { lazyConnect: true });',
  '  }',
  '',
  '  async onModuleInit() {',
  '    await this.client.connect();',
  '    this.logger.log("Redis connected");',
  '  }',
  '',
  '  async onModuleDestroy() {',
  '    await this.client.quit();',
  '  }',
  '}',
]);

write("infra/cache/cache.module.ts", [
  'import { Global, Module } from "@nestjs/common";',
  'import { RedisService } from "./redis.service";',
  '',
  '@Global()',
  '@Module({',
  '  providers: [RedisService],',
  '  exports: [RedisService],',
  '})',
  'export class CacheModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// AUTH
// ─────────────────────────────────────────────────────────────────────────────

write("modules/auth/dto/auth.dto.ts", [
  'import { z } from "zod";',
  '',
  'export const RegisterSchema = z.object({',
  '  email: z.string().email(),',
  '  password: z.string().min(8).max(128),',
  '  firstName: z.string().min(1).max(100),',
  '  lastName: z.string().max(100).optional(),',
  '});',
  'export type RegisterDto = z.infer<typeof RegisterSchema>;',
  '',
  'export const LoginSchema = z.object({',
  '  email: z.string().email(),',
  '  password: z.string().min(1),',
  '});',
  'export type LoginDto = z.infer<typeof LoginSchema>;',
]);

write("modules/auth/auth.repository.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  '',
  '@Injectable()',
  'export class AuthRepository {',
  '  constructor(private readonly prisma: PrismaService) {}',
  '',
  '  findByEmail(email: string) {',
  '    return this.prisma.user.findUnique({ where: { email } });',
  '  }',
  '',
  '  findById(id: string) {',
  '    return this.prisma.user.findUnique({ where: { id } });',
  '  }',
  '',
  '  create(data: { email: string; passwordHash: string; firstName: string; lastName?: string }) {',
  '    return this.prisma.user.create({ data });',
  '  }',
  '}',
]);

write("modules/auth/auth.service.ts", [
  'import { ConflictException, Injectable, UnauthorizedException } from "@nestjs/common";',
  'import { JwtService } from "@nestjs/jwt";',
  'import * as argon2 from "argon2";',
  'import { AuthRepository } from "./auth.repository";',
  'import type { LoginDto, RegisterDto } from "./dto/auth.dto";',
  'import { getEnv } from "@/config/env";',
  '',
  'export interface AuthTokens {',
  '  accessToken: string;',
  '  refreshToken: string;',
  '}',
  '',
  'export interface AuthResult extends AuthTokens {',
  '  user: { id: string; email: string; firstName: string; role: string };',
  '}',
  '',
  '@Injectable()',
  'export class AuthService {',
  '  constructor(',
  '    private readonly repo: AuthRepository,',
  '    private readonly jwt: JwtService,',
  '  ) {}',
  '',
  '  async register(dto: RegisterDto): Promise<AuthResult> {',
  '    const existing = await this.repo.findByEmail(dto.email);',
  '    if (existing) throw new ConflictException("Email already registered");',
  '    const passwordHash = await argon2.hash(dto.password);',
  '    const user = await this.repo.create({',
  '      email: dto.email,',
  '      passwordHash,',
  '      firstName: dto.firstName,',
  '      lastName: dto.lastName,',
  '    });',
  '    return this.issue(user);',
  '  }',
  '',
  '  async login(dto: LoginDto): Promise<AuthResult> {',
  '    const user = await this.repo.findByEmail(dto.email);',
  '    if (!user) throw new UnauthorizedException("Invalid credentials");',
  '    const ok = await argon2.verify(user.passwordHash, dto.password);',
  '    if (!ok) throw new UnauthorizedException("Invalid credentials");',
  '    return this.issue(user);',
  '  }',
  '',
  '  async me(userId: string) {',
  '    const user = await this.repo.findById(userId);',
  '    if (!user) throw new UnauthorizedException();',
  '    return {',
  '      id: user.id,',
  '      email: user.email,',
  '      firstName: user.firstName,',
  '      lastName: user.lastName,',
  '      role: user.role,',
  '    };',
  '  }',
  '',
  '  private async issue(user: { id: string; email: string; firstName: string; role: string }): Promise<AuthResult> {',
  '    const env = getEnv();',
  '    const payload = { sub: user.id, email: user.email, role: user.role };',
  '    const accessToken = await this.jwt.signAsync(payload, {',
  '      secret: env.JWT_ACCESS_SECRET,',
  '      expiresIn: env.JWT_ACCESS_TTL,',
  '    });',
  '    const refreshToken = await this.jwt.signAsync(payload, {',
  '      secret: env.JWT_REFRESH_SECRET,',
  '      expiresIn: env.JWT_REFRESH_TTL,',
  '    });',
  '    return {',
  '      accessToken,',
  '      refreshToken,',
  '      user: { id: user.id, email: user.email, firstName: user.firstName, role: user.role },',
  '    };',
  '  }',
  '}',
]);

write("modules/auth/auth.controller.ts", [
  'import { Body, Controller, Get, Post, UseGuards } from "@nestjs/common";',
  'import { AuthService } from "./auth.service";',
  'import { LoginSchema, RegisterSchema, type LoginDto, type RegisterDto } from "./dto/auth.dto";',
  'import { ZodValidationPipe } from "@/common/pipes/zod-validation.pipe";',
  'import { JwtGuard } from "@/common/guards/jwt.guard";',
  'import { CurrentUser, type AuthUser } from "@/common/decorators/current-user.decorator";',
  '',
  '@Controller("auth")',
  'export class AuthController {',
  '  constructor(private readonly auth: AuthService) {}',
  '',
  '  @Post("register")',
  '  register(@Body(new ZodValidationPipe(RegisterSchema)) dto: RegisterDto) {',
  '    return this.auth.register(dto);',
  '  }',
  '',
  '  @Post("login")',
  '  login(@Body(new ZodValidationPipe(LoginSchema)) dto: LoginDto) {',
  '    return this.auth.login(dto);',
  '  }',
  '',
  '  @UseGuards(JwtGuard)',
  '  @Get("me")',
  '  me(@CurrentUser() user: AuthUser) {',
  '    return this.auth.me(user.id);',
  '  }',
  '}',
]);

write("modules/auth/auth.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { JwtModule } from "@nestjs/jwt";',
  'import { AuthController } from "./auth.controller";',
  'import { AuthService } from "./auth.service";',
  'import { AuthRepository } from "./auth.repository";',
  '',
  '@Module({',
  '  imports: [JwtModule.register({})],',
  '  controllers: [AuthController],',
  '  providers: [AuthService, AuthRepository],',
  '  exports: [AuthService, JwtModule],',
  '})',
  'export class AuthModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// PRODUCTS
// ─────────────────────────────────────────────────────────────────────────────

write("modules/products/dto/list-products.dto.ts", [
  'import { z } from "zod";',
  '',
  'export const ListProductsQuerySchema = z.object({',
  '  category: z.string().optional(),',
  '  brand: z.string().optional(),',
  '  minPrice: z.coerce.number().optional(),',
  '  maxPrice: z.coerce.number().optional(),',
  '  minRating: z.coerce.number().min(0).max(5).optional(),',
  '  search: z.string().optional(),',
  '  sort: z.enum(["relevance", "price_asc", "price_desc", "rating", "newest"]).default("relevance"),',
  '  page: z.coerce.number().int().min(1).default(1),',
  '  limit: z.coerce.number().int().min(1).max(100).default(24),',
  '});',
  'export type ListProductsQuery = z.infer<typeof ListProductsQuerySchema>;',
]);

write("modules/products/product.mapper.ts", [
  'import type { Product as PrismaProduct, Brand, Category } from "@prisma/client";',
  '',
  'export interface ProductResponse {',
  '  id: string;',
  '  slug: string;',
  '  name: string;',
  '  brand: string;',
  '  category: string;',
  '  image: string;',
  '  imageAlt: string;',
  '  price: { amount: number; currency: string; formatted: string };',
  '  originalPrice?: { amount: number; currency: string; formatted: string };',
  '  discountPercent?: number;',
  '  rating: { value: number; count: number };',
  '  badge?: string;',
  '  stock: number;',
  '  freeShipping: boolean;',
  '}',
  '',
  'function fmt(amount: number, currency: string) {',
  '  return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(amount / 100);',
  '}',
  '',
  'export function toProductResponse(',
  '  p: PrismaProduct & { brand: Brand | null; category: Category },',
  '): ProductResponse {',
  '  return {',
  '    id: p.id,',
  '    slug: p.slug,',
  '    name: p.name,',
  '    brand: p.brand?.name ?? "",',
  '    category: p.category.slug,',
  '    image: p.image,',
  '    imageAlt: p.imageAlt,',
  '    price: { amount: p.priceAmount, currency: p.priceCurrency, formatted: fmt(p.priceAmount, p.priceCurrency) },',
  '    originalPrice: p.originalPrice',
  '      ? { amount: p.originalPrice, currency: p.priceCurrency, formatted: fmt(p.originalPrice, p.priceCurrency) }',
  '      : undefined,',
  '    discountPercent: p.discountPct ?? undefined,',
  '    rating: { value: p.rating, count: p.reviewCount },',
  '    badge: p.badge ?? undefined,',
  '    stock: p.stock,',
  '    freeShipping: p.freeShipping,',
  '  };',
  '}',
]);

write("modules/products/products.repository.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  'import type { Prisma } from "@prisma/client";',
  'import type { ListProductsQuery } from "./dto/list-products.dto";',
  '',
  '@Injectable()',
  'export class ProductsRepository {',
  '  constructor(private readonly prisma: PrismaService) {}',
  '',
  '  async list(q: ListProductsQuery) {',
  '    const where: Prisma.ProductWhereInput = {};',
  '    if (q.category) where.category = { slug: q.category };',
  '    if (q.brand) where.brand = { slug: q.brand };',
  '    if (q.minPrice !== undefined || q.maxPrice !== undefined) {',
  '      where.priceAmount = {};',
  '      if (q.minPrice !== undefined) where.priceAmount.gte = q.minPrice;',
  '      if (q.maxPrice !== undefined) where.priceAmount.lte = q.maxPrice;',
  '    }',
  '    if (q.minRating !== undefined) where.rating = { gte: q.minRating };',
  '    if (q.search) {',
  '      where.OR = [',
  '        { name: { contains: q.search, mode: "insensitive" } },',
  '        { description: { contains: q.search, mode: "insensitive" } },',
  '      ];',
  '    }',
  '    const orderBy: Prisma.ProductOrderByWithRelationInput =',
  '      q.sort === "price_asc" ? { priceAmount: "asc" }',
  '      : q.sort === "price_desc" ? { priceAmount: "desc" }',
  '      : q.sort === "rating" ? { rating: "desc" }',
  '      : q.sort === "newest" ? { createdAt: "desc" }',
  '      : { reviewCount: "desc" };',
  '    const skip = (q.page - 1) * q.limit;',
  '    const [items, total] = await Promise.all([',
  '      this.prisma.product.findMany({ where, orderBy, skip, take: q.limit, include: { brand: true, category: true } }),',
  '      this.prisma.product.count({ where }),',
  '    ]);',
  '    return { items, total };',
  '  }',
  '',
  '  findBySlug(slug: string) {',
  '    return this.prisma.product.findUnique({',
  '      where: { slug },',
  '      include: { brand: true, category: true },',
  '    });',
  '  }',
  '}',
]);

write("modules/products/products.service.ts", [
  'import { Injectable, NotFoundException } from "@nestjs/common";',
  'import { ProductsRepository } from "./products.repository";',
  'import { toProductResponse } from "./product.mapper";',
  'import type { ListProductsQuery } from "./dto/list-products.dto";',
  '',
  '@Injectable()',
  'export class ProductsService {',
  '  constructor(private readonly repo: ProductsRepository) {}',
  '',
  '  async list(q: ListProductsQuery) {',
  '    const { items, total } = await this.repo.list(q);',
  '    return {',
  '      items: items.map(toProductResponse),',
  '      total,',
  '      page: q.page,',
  '      limit: q.limit,',
  '      pageCount: Math.ceil(total / q.limit),',
  '    };',
  '  }',
  '',
  '  async getBySlug(slug: string) {',
  '    const product = await this.repo.findBySlug(slug);',
  '    if (!product) throw new NotFoundException("Product not found");',
  '    return toProductResponse(product);',
  '  }',
  '}',
]);

write("modules/products/products.controller.ts", [
  'import { Controller, Get, Param, Query } from "@nestjs/common";',
  'import { ProductsService } from "./products.service";',
  'import { ListProductsQuerySchema, type ListProductsQuery } from "./dto/list-products.dto";',
  'import { ZodValidationPipe } from "@/common/pipes/zod-validation.pipe";',
  '',
  '@Controller("products")',
  'export class ProductsController {',
  '  constructor(private readonly products: ProductsService) {}',
  '',
  '  @Get()',
  '  list(@Query(new ZodValidationPipe(ListProductsQuerySchema)) q: ListProductsQuery) {',
  '    return this.products.list(q);',
  '  }',
  '',
  '  @Get(":slug")',
  '  getOne(@Param("slug") slug: string) {',
  '    return this.products.getBySlug(slug);',
  '  }',
  '}',
]);

write("modules/products/products.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { ProductsController } from "./products.controller";',
  'import { ProductsService } from "./products.service";',
  'import { ProductsRepository } from "./products.repository";',
  '',
  '@Module({',
  '  controllers: [ProductsController],',
  '  providers: [ProductsService, ProductsRepository],',
  '  exports: [ProductsService],',
  '})',
  'export class ProductsModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// CATEGORIES
// ─────────────────────────────────────────────────────────────────────────────

write("modules/categories/categories.repository.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  '',
  '@Injectable()',
  'export class CategoriesRepository {',
  '  constructor(private readonly prisma: PrismaService) {}',
  '',
  '  list() {',
  '    return this.prisma.category.findMany({',
  '      where: { parentId: null },',
  '      include: { children: true },',
  '      orderBy: { name: "asc" },',
  '    });',
  '  }',
  '',
  '  findBySlug(slug: string) {',
  '    return this.prisma.category.findUnique({ where: { slug } });',
  '  }',
  '}',
]);

write("modules/categories/categories.service.ts", [
  'import { Injectable, NotFoundException } from "@nestjs/common";',
  'import { CategoriesRepository } from "./categories.repository";',
  '',
  '@Injectable()',
  'export class CategoriesService {',
  '  constructor(private readonly repo: CategoriesRepository) {}',
  '',
  '  list() { return this.repo.list(); }',
  '',
  '  async getBySlug(slug: string) {',
  '    const c = await this.repo.findBySlug(slug);',
  '    if (!c) throw new NotFoundException("Category not found");',
  '    return c;',
  '  }',
  '}',
]);

write("modules/categories/categories.controller.ts", [
  'import { Controller, Get, Param } from "@nestjs/common";',
  'import { CategoriesService } from "./categories.service";',
  '',
  '@Controller("categories")',
  'export class CategoriesController {',
  '  constructor(private readonly categories: CategoriesService) {}',
  '',
  '  @Get() list() { return this.categories.list(); }',
  '',
  '  @Get(":slug")',
  '  getOne(@Param("slug") slug: string) { return this.categories.getBySlug(slug); }',
  '}',
]);

write("modules/categories/categories.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { CategoriesController } from "./categories.controller";',
  'import { CategoriesService } from "./categories.service";',
  'import { CategoriesRepository } from "./categories.repository";',
  '',
  '@Module({',
  '  controllers: [CategoriesController],',
  '  providers: [CategoriesService, CategoriesRepository],',
  '})',
  'export class CategoriesModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// BRANDS
// ─────────────────────────────────────────────────────────────────────────────

write("modules/brands/brands.repository.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  '',
  '@Injectable()',
  'export class BrandsRepository {',
  '  constructor(private readonly prisma: PrismaService) {}',
  '',
  '  list() { return this.prisma.brand.findMany({ orderBy: { name: "asc" } }); }',
  '',
  '  findBySlug(slug: string) {',
  '    return this.prisma.brand.findUnique({ where: { slug } });',
  '  }',
  '}',
]);

write("modules/brands/brands.service.ts", [
  'import { Injectable, NotFoundException } from "@nestjs/common";',
  'import { BrandsRepository } from "./brands.repository";',
  '',
  '@Injectable()',
  'export class BrandsService {',
  '  constructor(private readonly repo: BrandsRepository) {}',
  '',
  '  list() { return this.repo.list(); }',
  '',
  '  async getBySlug(slug: string) {',
  '    const b = await this.repo.findBySlug(slug);',
  '    if (!b) throw new NotFoundException("Brand not found");',
  '    return b;',
  '  }',
  '}',
]);

write("modules/brands/brands.controller.ts", [
  'import { Controller, Get, Param } from "@nestjs/common";',
  'import { BrandsService } from "./brands.service";',
  '',
  '@Controller("brands")',
  'export class BrandsController {',
  '  constructor(private readonly brands: BrandsService) {}',
  '',
  '  @Get() list() { return this.brands.list(); }',
  '',
  '  @Get(":slug")',
  '  getOne(@Param("slug") slug: string) { return this.brands.getBySlug(slug); }',
  '}',
]);

write("modules/brands/brands.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { BrandsController } from "./brands.controller";',
  'import { BrandsService } from "./brands.service";',
  'import { BrandsRepository } from "./brands.repository";',
  '',
  '@Module({',
  '  controllers: [BrandsController],',
  '  providers: [BrandsService, BrandsRepository],',
  '})',
  'export class BrandsModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// CART
// ─────────────────────────────────────────────────────────────────────────────

write("modules/cart/dto/cart.dto.ts", [
  'import { z } from "zod";',
  '',
  'export const AddCartItemSchema = z.object({',
  '  productId: z.string().min(1),',
  '  quantity: z.coerce.number().int().min(1).max(99).default(1),',
  '});',
  'export type AddCartItemDto = z.infer<typeof AddCartItemSchema>;',
  '',
  'export const UpdateCartItemSchema = z.object({',
  '  quantity: z.coerce.number().int().min(0).max(99),',
  '});',
  'export type UpdateCartItemDto = z.infer<typeof UpdateCartItemSchema>;',
]);

write("modules/cart/cart.repository.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  '',
  '@Injectable()',
  'export class CartRepository {',
  '  constructor(private readonly prisma: PrismaService) {}',
  '',
  '  findByUserId(userId: string) {',
  '    return this.prisma.cart.findFirst({',
  '      where: { userId },',
  '      include: { items: { include: { product: true } } },',
  '    });',
  '  }',
  '',
  '  createForUser(userId: string) {',
  '    return this.prisma.cart.create({',
  '      data: { userId },',
  '      include: { items: { include: { product: true } } },',
  '    });',
  '  }',
  '',
  '  async ensureForUser(userId: string) {',
  '    const existing = await this.findByUserId(userId);',
  '    return existing ?? (await this.createForUser(userId));',
  '  }',
  '',
  '  upsertItem(cartId: string, productId: string, quantity: number) {',
  '    return this.prisma.cartItem.upsert({',
  '      where: { cartId_productId: { cartId, productId } },',
  '      create: { cartId, productId, quantity },',
  '      update: { quantity },',
  '    });',
  '  }',
  '',
  '  removeItem(cartId: string, productId: string) {',
  '    return this.prisma.cartItem.deleteMany({ where: { cartId, productId } });',
  '  }',
  '',
  '  clear(cartId: string) {',
  '    return this.prisma.cartItem.deleteMany({ where: { cartId } });',
  '  }',
  '}',
]);

write("modules/cart/cart.service.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { CartRepository } from "./cart.repository";',
  '',
  '@Injectable()',
  'export class CartService {',
  '  constructor(private readonly repo: CartRepository) {}',
  '',
  '  async get(userId: string) {',
  '    const cart = await this.repo.ensureForUser(userId);',
  '    return this.summarize(cart);',
  '  }',
  '',
  '  async addItem(userId: string, productId: string, quantity: number) {',
  '    const cart = await this.repo.ensureForUser(userId);',
  '    const existing = cart.items.find((i) => i.productId === productId);',
  '    const nextQty = (existing?.quantity ?? 0) + quantity;',
  '    await this.repo.upsertItem(cart.id, productId, nextQty);',
  '    return this.get(userId);',
  '  }',
  '',
  '  async updateItem(userId: string, productId: string, quantity: number) {',
  '    const cart = await this.repo.ensureForUser(userId);',
  '    if (quantity <= 0) await this.repo.removeItem(cart.id, productId);',
  '    else await this.repo.upsertItem(cart.id, productId, quantity);',
  '    return this.get(userId);',
  '  }',
  '',
  '  async removeItem(userId: string, productId: string) {',
  '    const cart = await this.repo.ensureForUser(userId);',
  '    await this.repo.removeItem(cart.id, productId);',
  '    return this.get(userId);',
  '  }',
  '',
  '  async clear(userId: string) {',
  '    const cart = await this.repo.ensureForUser(userId);',
  '    await this.repo.clear(cart.id);',
  '    return this.get(userId);',
  '  }',
  '',
  '  private summarize(cart: { items: Array<{ productId: string; quantity: number; product: { priceAmount: number; priceCurrency: string; name: string; image: string; slug: string } }> }) {',
  '    const items = cart.items.map((i) => ({',
  '      productId: i.productId,',
  '      slug: i.product.slug,',
  '      name: i.product.name,',
  '      image: i.product.image,',
  '      unitPrice: i.product.priceAmount,',
  '      currency: i.product.priceCurrency,',
  '      quantity: i.quantity,',
  '      lineTotal: i.product.priceAmount * i.quantity,',
  '    }));',
  '    const itemCount = items.reduce((n, i) => n + i.quantity, 0);',
  '    const subtotal = items.reduce((n, i) => n + i.lineTotal, 0);',
  '    return { items, itemCount, subtotal, currency: "USD" };',
  '  }',
  '}',
]);

write("modules/cart/cart.controller.ts", [
  'import { Body, Controller, Delete, Get, Param, Patch, Post, UseGuards } from "@nestjs/common";',
  'import { CartService } from "./cart.service";',
  'import { AddCartItemSchema, UpdateCartItemSchema, type AddCartItemDto, type UpdateCartItemDto } from "./dto/cart.dto";',
  'import { ZodValidationPipe } from "@/common/pipes/zod-validation.pipe";',
  'import { JwtGuard } from "@/common/guards/jwt.guard";',
  'import { CurrentUser, type AuthUser } from "@/common/decorators/current-user.decorator";',
  '',
  '@UseGuards(JwtGuard)',
  '@Controller("cart")',
  'export class CartController {',
  '  constructor(private readonly cart: CartService) {}',
  '',
  '  @Get()',
  '  get(@CurrentUser() user: AuthUser) { return this.cart.get(user.id); }',
  '',
  '  @Post("items")',
  '  add(@CurrentUser() user: AuthUser, @Body(new ZodValidationPipe(AddCartItemSchema)) dto: AddCartItemDto) {',
  '    return this.cart.addItem(user.id, dto.productId, dto.quantity);',
  '  }',
  '',
  '  @Patch("items/:productId")',
  '  update(@CurrentUser() user: AuthUser, @Param("productId") productId: string, @Body(new ZodValidationPipe(UpdateCartItemSchema)) dto: UpdateCartItemDto) {',
  '    return this.cart.updateItem(user.id, productId, dto.quantity);',
  '  }',
  '',
  '  @Delete("items/:productId")',
  '  remove(@CurrentUser() user: AuthUser, @Param("productId") productId: string) {',
  '    return this.cart.removeItem(user.id, productId);',
  '  }',
  '',
  '  @Delete()',
  '  clear(@CurrentUser() user: AuthUser) { return this.cart.clear(user.id); }',
  '}',
]);

write("modules/cart/cart.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { JwtModule } from "@nestjs/jwt";',
  'import { CartController } from "./cart.controller";',
  'import { CartService } from "./cart.service";',
  'import { CartRepository } from "./cart.repository";',
  '',
  '@Module({',
  '  imports: [JwtModule.register({})],',
  '  controllers: [CartController],',
  '  providers: [CartService, CartRepository],',
  '})',
  'export class CartModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// WISHLIST
// ─────────────────────────────────────────────────────────────────────────────

write("modules/wishlist/wishlist.repository.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  '',
  '@Injectable()',
  'export class WishlistRepository {',
  '  constructor(private readonly prisma: PrismaService) {}',
  '',
  '  list(userId: string) {',
  '    return this.prisma.wishlistItem.findMany({',
  '      where: { userId },',
  '      include: { product: true },',
  '      orderBy: { addedAt: "desc" },',
  '    });',
  '  }',
  '',
  '  add(userId: string, productId: string) {',
  '    return this.prisma.wishlistItem.upsert({',
  '      where: { userId_productId: { userId, productId } },',
  '      create: { userId, productId },',
  '      update: {},',
  '    });',
  '  }',
  '',
  '  remove(userId: string, productId: string) {',
  '    return this.prisma.wishlistItem.deleteMany({ where: { userId, productId } });',
  '  }',
  '}',
]);

write("modules/wishlist/wishlist.service.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { WishlistRepository } from "./wishlist.repository";',
  '',
  '@Injectable()',
  'export class WishlistService {',
  '  constructor(private readonly repo: WishlistRepository) {}',
  '',
  '  list(userId: string) { return this.repo.list(userId); }',
  '  add(userId: string, productId: string) { return this.repo.add(userId, productId); }',
  '  remove(userId: string, productId: string) { return this.repo.remove(userId, productId); }',
  '}',
]);

write("modules/wishlist/wishlist.controller.ts", [
  'import { Controller, Delete, Get, Param, Post, UseGuards } from "@nestjs/common";',
  'import { WishlistService } from "./wishlist.service";',
  'import { JwtGuard } from "@/common/guards/jwt.guard";',
  'import { CurrentUser, type AuthUser } from "@/common/decorators/current-user.decorator";',
  '',
  '@UseGuards(JwtGuard)',
  '@Controller("wishlist")',
  'export class WishlistController {',
  '  constructor(private readonly wishlist: WishlistService) {}',
  '',
  '  @Get()',
  '  list(@CurrentUser() user: AuthUser) { return this.wishlist.list(user.id); }',
  '',
  '  @Post(":productId")',
  '  add(@CurrentUser() user: AuthUser, @Param("productId") productId: string) {',
  '    return this.wishlist.add(user.id, productId);',
  '  }',
  '',
  '  @Delete(":productId")',
  '  remove(@CurrentUser() user: AuthUser, @Param("productId") productId: string) {',
  '    return this.wishlist.remove(user.id, productId);',
  '  }',
  '}',
]);

write("modules/wishlist/wishlist.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { JwtModule } from "@nestjs/jwt";',
  'import { WishlistController } from "./wishlist.controller";',
  'import { WishlistService } from "./wishlist.service";',
  'import { WishlistRepository } from "./wishlist.repository";',
  '',
  '@Module({',
  '  imports: [JwtModule.register({})],',
  '  controllers: [WishlistController],',
  '  providers: [WishlistService, WishlistRepository],',
  '})',
  'export class WishlistModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// ORDERS
// ─────────────────────────────────────────────────────────────────────────────

write("modules/orders/orders.repository.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  '',
  '@Injectable()',
  'export class OrdersRepository {',
  '  constructor(private readonly prisma: PrismaService) {}',
  '',
  '  listByUser(userId: string) {',
  '    return this.prisma.order.findMany({',
  '      where: { userId },',
  '      include: { items: { include: { product: true } } },',
  '      orderBy: { createdAt: "desc" },',
  '    });',
  '  }',
  '',
  '  findById(id: string) {',
  '    return this.prisma.order.findUnique({',
  '      where: { id },',
  '      include: { items: { include: { product: true } } },',
  '    });',
  '  }',
  '',
  '  create(userId: string, items: { productId: string; quantity: number; unitPrice: number }[]) {',
  '    const total = items.reduce((n, i) => n + i.unitPrice * i.quantity, 0);',
  '    return this.prisma.order.create({',
  '      data: {',
  '        userId,',
  '        total,',
  '        status: "pending",',
  '        items: { create: items.map((i) => ({ productId: i.productId, quantity: i.quantity, unitPrice: i.unitPrice })) },',
  '      },',
  '      include: { items: { include: { product: true } } },',
  '    });',
  '  }',
  '}',
]);

write("modules/orders/orders.service.ts", [
  'import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";',
  'import { OrdersRepository } from "./orders.repository";',
  'import { CartRepository } from "../cart/cart.repository";',
  '',
  '@Injectable()',
  'export class OrdersService {',
  '  constructor(',
  '    private readonly orders: OrdersRepository,',
  '    private readonly carts: CartRepository,',
  '  ) {}',
  '',
  '  list(userId: string) { return this.orders.listByUser(userId); }',
  '',
  '  async getOne(userId: string, id: string) {',
  '    const order = await this.orders.findById(id);',
  '    if (!order || order.userId !== userId) throw new NotFoundException("Order not found");',
  '    return order;',
  '  }',
  '',
  '  async checkout(userId: string) {',
  '    const cart = await this.carts.findByUserId(userId);',
  '    if (!cart || cart.items.length === 0) throw new BadRequestException("Cart is empty");',
  '    const items = cart.items.map((i) => ({',
  '      productId: i.productId,',
  '      quantity: i.quantity,',
  '      unitPrice: i.product.priceAmount,',
  '    }));',
  '    const order = await this.orders.create(userId, items);',
  '    await this.carts.clear(cart.id);',
  '    return order;',
  '  }',
  '}',
]);

write("modules/orders/orders.controller.ts", [
  'import { Controller, Get, Param, Post, UseGuards } from "@nestjs/common";',
  'import { OrdersService } from "./orders.service";',
  'import { JwtGuard } from "@/common/guards/jwt.guard";',
  'import { CurrentUser, type AuthUser } from "@/common/decorators/current-user.decorator";',
  '',
  '@UseGuards(JwtGuard)',
  '@Controller("orders")',
  'export class OrdersController {',
  '  constructor(private readonly orders: OrdersService) {}',
  '',
  '  @Post()',
  '  checkout(@CurrentUser() user: AuthUser) { return this.orders.checkout(user.id); }',
  '',
  '  @Get()',
  '  list(@CurrentUser() user: AuthUser) { return this.orders.list(user.id); }',
  '',
  '  @Get(":id")',
  '  getOne(@CurrentUser() user: AuthUser, @Param("id") id: string) {',
  '    return this.orders.getOne(user.id, id);',
  '  }',
  '}',
]);

write("modules/orders/orders.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { JwtModule } from "@nestjs/jwt";',
  'import { OrdersController } from "./orders.controller";',
  'import { OrdersService } from "./orders.service";',
  'import { OrdersRepository } from "./orders.repository";',
  'import { CartRepository } from "../cart/cart.repository";',
  '',
  '@Module({',
  '  imports: [JwtModule.register({})],',
  '  controllers: [OrdersController],',
  '  providers: [OrdersService, OrdersRepository, CartRepository],',
  '})',
  'export class OrdersModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// REVIEWS
// ─────────────────────────────────────────────────────────────────────────────

write("modules/reviews/dto/review.dto.ts", [
  'import { z } from "zod";',
  '',
  'export const CreateReviewSchema = z.object({',
  '  rating: z.coerce.number().int().min(1).max(5),',
  '  title: z.string().max(200).optional(),',
  '  body: z.string().max(5000).optional(),',
  '});',
  'export type CreateReviewDto = z.infer<typeof CreateReviewSchema>;',
]);

write("modules/reviews/reviews.repository.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  '',
  '@Injectable()',
  'export class ReviewsRepository {',
  '  constructor(private readonly prisma: PrismaService) {}',
  '',
  '  listByProductSlug(slug: string) {',
  '    return this.prisma.review.findMany({',
  '      where: { product: { slug } },',
  '      include: { user: { select: { firstName: true, lastName: true } } },',
  '      orderBy: { createdAt: "desc" },',
  '    });',
  '  }',
  '',
  '  create(userId: string, productId: string, dto: { rating: number; title?: string; body?: string }) {',
  '    return this.prisma.review.create({',
  '      data: { userId, productId, rating: dto.rating, title: dto.title, body: dto.body },',
  '    });',
  '  }',
  '}',
]);

write("modules/reviews/reviews.service.ts", [
  'import { Injectable, NotFoundException } from "@nestjs/common";',
  'import { ReviewsRepository } from "./reviews.repository";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  '',
  '@Injectable()',
  'export class ReviewsService {',
  '  constructor(',
  '    private readonly repo: ReviewsRepository,',
  '    private readonly prisma: PrismaService,',
  '  ) {}',
  '',
  '  list(productSlug: string) { return this.repo.listByProductSlug(productSlug); }',
  '',
  '  async createForSlug(userId: string, productSlug: string, dto: { rating: number; title?: string; body?: string }) {',
  '    const product = await this.prisma.product.findUnique({ where: { slug: productSlug } });',
  '    if (!product) throw new NotFoundException("Product not found");',
  '    return this.repo.create(userId, product.id, dto);',
  '  }',
  '}',
]);

write("modules/reviews/reviews.controller.ts", [
  'import { Body, Controller, Get, Param, Post, UseGuards } from "@nestjs/common";',
  'import { ReviewsService } from "./reviews.service";',
  'import { CreateReviewSchema, type CreateReviewDto } from "./dto/review.dto";',
  'import { ZodValidationPipe } from "@/common/pipes/zod-validation.pipe";',
  'import { JwtGuard } from "@/common/guards/jwt.guard";',
  'import { CurrentUser, type AuthUser } from "@/common/decorators/current-user.decorator";',
  '',
  '@Controller("products/:slug/reviews")',
  'export class ReviewsController {',
  '  constructor(private readonly reviews: ReviewsService) {}',
  '',
  '  @Get()',
  '  list(@Param("slug") slug: string) { return this.reviews.list(slug); }',
  '',
  '  @UseGuards(JwtGuard)',
  '  @Post()',
  '  create(@CurrentUser() user: AuthUser, @Param("slug") slug: string, @Body(new ZodValidationPipe(CreateReviewSchema)) dto: CreateReviewDto) {',
  '    return this.reviews.createForSlug(user.id, slug, dto);',
  '  }',
  '}',
]);

write("modules/reviews/reviews.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { JwtModule } from "@nestjs/jwt";',
  'import { ReviewsController } from "./reviews.controller";',
  'import { ReviewsService } from "./reviews.service";',
  'import { ReviewsRepository } from "./reviews.repository";',
  '',
  '@Module({',
  '  imports: [JwtModule.register({})],',
  '  controllers: [ReviewsController],',
  '  providers: [ReviewsService, ReviewsRepository],',
  '})',
  'export class ReviewsModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// RECENTLY VIEWED
// ─────────────────────────────────────────────────────────────────────────────

write("modules/recently-viewed/recently-viewed.repository.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  '',
  '@Injectable()',
  'export class RecentlyViewedRepository {',
  '  constructor(private readonly prisma: PrismaService) {}',
  '',
  '  list(userId: string, limit = 20) {',
  '    return this.prisma.recentlyViewed.findMany({',
  '      where: { userId },',
  '      include: { product: true },',
  '      orderBy: { viewedAt: "desc" },',
  '      take: limit,',
  '    });',
  '  }',
  '',
  '  record(userId: string, productId: string) {',
  '    return this.prisma.recentlyViewed.upsert({',
  '      where: { userId_productId: { userId, productId } },',
  '      create: { userId, productId },',
  '      update: { viewedAt: new Date() },',
  '    });',
  '  }',
  '}',
]);

write("modules/recently-viewed/recently-viewed.service.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { RecentlyViewedRepository } from "./recently-viewed.repository";',
  '',
  '@Injectable()',
  'export class RecentlyViewedService {',
  '  constructor(private readonly repo: RecentlyViewedRepository) {}',
  '  list(userId: string) { return this.repo.list(userId); }',
  '  record(userId: string, productId: string) { return this.repo.record(userId, productId); }',
  '}',
]);

write("modules/recently-viewed/recently-viewed.controller.ts", [
  'import { Controller, Get, Param, Post, UseGuards } from "@nestjs/common";',
  'import { RecentlyViewedService } from "./recently-viewed.service";',
  'import { JwtGuard } from "@/common/guards/jwt.guard";',
  'import { CurrentUser, type AuthUser } from "@/common/decorators/current-user.decorator";',
  '',
  '@UseGuards(JwtGuard)',
  '@Controller("recently-viewed")',
  'export class RecentlyViewedController {',
  '  constructor(private readonly rv: RecentlyViewedService) {}',
  '',
  '  @Get()',
  '  list(@CurrentUser() user: AuthUser) { return this.rv.list(user.id); }',
  '',
  '  @Post(":productId")',
  '  record(@CurrentUser() user: AuthUser, @Param("productId") productId: string) {',
  '    return this.rv.record(user.id, productId);',
  '  }',
  '}',
]);

write("modules/recently-viewed/recently-viewed.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { JwtModule } from "@nestjs/jwt";',
  'import { RecentlyViewedController } from "./recently-viewed.controller";',
  'import { RecentlyViewedService } from "./recently-viewed.service";',
  'import { RecentlyViewedRepository } from "./recently-viewed.repository";',
  '',
  '@Module({',
  '  imports: [JwtModule.register({})],',
  '  controllers: [RecentlyViewedController],',
  '  providers: [RecentlyViewedService, RecentlyViewedRepository],',
  '})',
  'export class RecentlyViewedModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// RECOMMENDATIONS
// ─────────────────────────────────────────────────────────────────────────────

write("modules/recommendations/recommendations.service.ts", [
  'import { Injectable } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  '',
  '@Injectable()',
  'export class RecommendationsService {',
  '  constructor(private readonly prisma: PrismaService) {}',
  '',
  '  async forUser(userId: string) {',
  '    const viewed = await this.prisma.recentlyViewed.findMany({',
  '      where: { userId },',
  '      include: { product: { include: { category: true } } },',
  '      orderBy: { viewedAt: "desc" },',
  '      take: 5,',
  '    });',
  '    const categoryIds = Array.from(new Set(viewed.map((v) => v.product.categoryId)));',
  '    if (categoryIds.length === 0) {',
  '      return this.prisma.product.findMany({ orderBy: { rating: "desc" }, take: 8, include: { brand: true, category: true } });',
  '    }',
  '    return this.prisma.product.findMany({',
  '      where: { categoryId: { in: categoryIds } },',
  '      orderBy: { rating: "desc" },',
  '      take: 8,',
  '      include: { brand: true, category: true },',
  '    });',
  '  }',
  '}',
]);

write("modules/recommendations/recommendations.controller.ts", [
  'import { Controller, Get, UseGuards } from "@nestjs/common";',
  'import { RecommendationsService } from "./recommendations.service";',
  'import { JwtGuard } from "@/common/guards/jwt.guard";',
  'import { CurrentUser, type AuthUser } from "@/common/decorators/current-user.decorator";',
  '',
  '@UseGuards(JwtGuard)',
  '@Controller("recommendations")',
  'export class RecommendationsController {',
  '  constructor(private readonly recs: RecommendationsService) {}',
  '',
  '  @Get()',
  '  list(@CurrentUser() user: AuthUser) { return this.recs.forUser(user.id); }',
  '}',
]);

write("modules/recommendations/recommendations.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { JwtModule } from "@nestjs/jwt";',
  'import { RecommendationsController } from "./recommendations.controller";',
  'import { RecommendationsService } from "./recommendations.service";',
  '',
  '@Module({',
  '  imports: [JwtModule.register({})],',
  '  controllers: [RecommendationsController],',
  '  providers: [RecommendationsService],',
  '})',
  'export class RecommendationsModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// NEWSLETTER
// ─────────────────────────────────────────────────────────────────────────────

write("modules/newsletter/dto/newsletter.dto.ts", [
  'import { z } from "zod";',
  '',
  'export const SubscribeSchema = z.object({',
  '  email: z.string().email(),',
  '});',
  'export type SubscribeDto = z.infer<typeof SubscribeSchema>;',
]);

write("modules/newsletter/newsletter.service.ts", [
  'import { Injectable, Logger } from "@nestjs/common";',
  'import type { SubscribeDto } from "./dto/newsletter.dto";',
  '',
  '@Injectable()',
  'export class NewsletterService {',
  '  private readonly logger = new Logger(NewsletterService.name);',
  '',
  '  async subscribe(dto: SubscribeDto) {',
  '    // Persist to newsletter table when you add one. For now: log.\\n    ',
  '    this.logger.log(`Newsletter subscription: ${dto.email}`);',
  '    return { ok: true };',
  '  }',
  '}',
]);

write("modules/newsletter/newsletter.controller.ts", [
  'import { Body, Controller, Post } from "@nestjs/common";',
  'import { NewsletterService } from "./newsletter.service";',
  'import { SubscribeSchema, type SubscribeDto } from "./dto/newsletter.dto";',
  'import { ZodValidationPipe } from "@/common/pipes/zod-validation.pipe";',
  '',
  '@Controller("newsletter")',
  'export class NewsletterController {',
  '  constructor(private readonly newsletter: NewsletterService) {}',
  '',
  '  @Post("subscribe")',
  '  subscribe(@Body(new ZodValidationPipe(SubscribeSchema)) dto: SubscribeDto) {',
  '    return this.newsletter.subscribe(dto);',
  '  }',
  '}',
]);

write("modules/newsletter/newsletter.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { NewsletterController } from "./newsletter.controller";',
  'import { NewsletterService } from "./newsletter.service";',
  '',
  '@Module({',
  '  controllers: [NewsletterController],',
  '  providers: [NewsletterService],',
  '})',
  'export class NewsletterModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// HEALTH
// ─────────────────────────────────────────────────────────────────────────────

write("modules/health/health.controller.ts", [
  'import { Controller, Get } from "@nestjs/common";',
  'import { PrismaService } from "@/infra/database/prisma.service";',
  'import { RedisService } from "@/infra/cache/redis.service";',
  '',
  '@Controller("health")',
  'export class HealthController {',
  '  constructor(',
  '    private readonly prisma: PrismaService,',
  '    private readonly redis: RedisService,',
  '  ) {}',
  '',
  '  @Get()',
  '  async check() {',
  '    let db = "up";',
  '    let cache = "up";',
  '    try { await this.prisma.$queryRaw`SELECT 1`; } catch { db = "down"; }',
  '    try { await this.redis.client.ping(); } catch { cache = "down"; }',
  '    return { status: db === "up" && cache === "up" ? "ok" : "degraded", db, cache };',
  '  }',
  '}',
]);

write("modules/health/health.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { HealthController } from "./health.controller";',
  '',
  '@Module({ controllers: [HealthController] })',
  'export class HealthModule {}',
]);

// ─────────────────────────────────────────────────────────────────────────────
// APP MODULE + MAIN
// ─────────────────────────────────────────────────────────────────────────────

write("app.module.ts", [
  'import { Module } from "@nestjs/common";',
  'import { ConfigModule } from "./config/config.module";',
  'import { DatabaseModule } from "./infra/database/database.module";',
  'import { CacheModule } from "./infra/cache/cache.module";',
  'import { AuthModule } from "./modules/auth/auth.module";',
  'import { ProductsModule } from "./modules/products/products.module";',
  'import { CategoriesModule } from "./modules/categories/categories.module";',
  'import { BrandsModule } from "./modules/brands/brands.module";',
  'import { CartModule } from "./modules/cart/cart.module";',
  'import { WishlistModule } from "./modules/wishlist/wishlist.module";',
  'import { OrdersModule } from "./modules/orders/orders.module";',
  'import { ReviewsModule } from "./modules/reviews/reviews.module";',
  'import { RecentlyViewedModule } from "./modules/recently-viewed/recently-viewed.module";',
  'import { RecommendationsModule } from "./modules/recommendations/recommendations.module";',
  'import { NewsletterModule } from "./modules/newsletter/newsletter.module";',
  'import { HealthModule } from "./modules/health/health.module";',
  '',
  '@Module({',
  '  imports: [',
  '    ConfigModule,',
  '    DatabaseModule,',
  '    CacheModule,',
  '    AuthModule,',
  '    ProductsModule,',
  '    CategoriesModule,',
  '    BrandsModule,',
  '    CartModule,',
  '    WishlistModule,',
  '    OrdersModule,',
  '    ReviewsModule,',
  '    RecentlyViewedModule,',
  '    RecommendationsModule,',
  '    NewsletterModule,',
  '    HealthModule,',
  '  ],',
  '})',
  'export class AppModule {}',
]);

write("main.ts", [
  'import { NestFactory } from "@nestjs/core";',
  'import { FastifyAdapter, type NestFastifyApplication } from "@nestjs/platform-fastify";',
  'import { Logger } from "@nestjs/common";',
  'import { AppModule } from "./app.module";',
  'import { HttpExceptionFilter } from "./common/filters/http-exception.filter";',
  'import { ResponseInterceptor } from "./common/interceptors/response.interceptor";',
  'import { getEnv } from "./config/env";',
  '',
  'async function bootstrap() {',
  '  const env = getEnv();',
  '  const app = await NestFactory.create<NestFastifyApplication>(',
  '    AppModule,',
  '    new FastifyAdapter({ trustProxy: true }),',
  '  );',
  '',
  '  app.setGlobalPrefix("api/v1");',
  '  app.useGlobalFilters(new HttpExceptionFilter());',
  '  app.useGlobalInterceptors(new ResponseInterceptor());',
  '  app.enableCors({',
  '    origin: env.FRONTEND_URL.split(","),',
  '    credentials: true,',
  '  });',
  '  app.enableShutdownHooks();',
  '',
  '  await app.listen(env.PORT, "0.0.0.0");',
  '  Logger.log(`API running on http://localhost:${env.PORT}/api/v1`, "Bootstrap");',
  '}',
  '',
  'bootstrap();',
]);

// ─────────────────────────────────────────────────────────────────────────────

console.log(`\n\x1b[32m✅ Backend scaffold complete\x1b[0m`);
console.log(`   created: ${counters.created}`);
console.log(`   skipped: ${counters.skipped}\n`);
console.log("Next steps:");
console.log("  npx prisma migrate dev --name init");
console.log("  npx prisma generate");
console.log("  npm run dev\n");