#!/usr/bin/env node
/**
 * PR 6 — Final page orchestrator. (FIXED — no template literal collisions)
 */

import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const SRC = path.join(ROOT, "src");

let written = 0;
function write(relPath, content) {
  const full = path.join(SRC, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
  console.log(`  \x1b[32m\u2713\x1b[0m src/${relPath}`);
  written++;
}

// ─────────────────────────────────────────────────────────────────────────────

write("features/home/hooks/useHomeHandlers.ts", [
'"use client";',
'import { useCallback, useState } from "react";',
'import type { Product } from "@/domain/product.types";',
'import { useAppDispatch } from "@/store/hooks";',
'import { markLastAdded, openMiniCart, closeMiniCart } from "@/store/slices/cart-ui.slice";',
'import { toggleOptimistic } from "@/store/slices/wishlist-ui.slice";',
'',
'export interface HomeHandlers {',
'  cartOpen: boolean;',
'  wishlistOpen: boolean;',
'  quickViewProduct: Product | null;',
'  handleAddToCart: (p: Product) => void;',
'  handleToggleWishlist: (p: Product) => void;',
'  handleQuickView: (p: Product) => void;',
'  handleOpenCart: () => void;',
'  handleCloseCart: () => void;',
'  openWishlist: () => void;',
'  closeWishlist: () => void;',
'  closeQuickView: () => void;',
'}',
'',
'export function useHomeHandlers(): HomeHandlers {',
'  const dispatch = useAppDispatch();',
'  const [cartOpen, setCartOpen] = useState(false);',
'  const [wishlistOpen, setWishlistOpen] = useState(false);',
'  const [quickViewProduct, setQuickViewProduct] = useState<Product | null>(null);',
'',
'  const handleAddToCart = useCallback(',
'    (p: Product) => {',
'      dispatch(markLastAdded(p.id));',
'      dispatch(openMiniCart());',
'      setCartOpen(true);',
'    },',
'    [dispatch],',
'  );',
'',
'  const handleToggleWishlist = useCallback(',
'    (p: Product) => {',
'      dispatch(toggleOptimistic(p.id));',
'    },',
'    [dispatch],',
'  );',
'',
'  const handleQuickView = useCallback((p: Product) => setQuickViewProduct(p), []);',
'  const closeQuickView = useCallback(() => setQuickViewProduct(null), []);',
'',
'  const handleOpenCart = useCallback(() => {',
'    setCartOpen(true);',
'    dispatch(openMiniCart());',
'  }, [dispatch]);',
'',
'  const handleCloseCart = useCallback(() => {',
'    setCartOpen(false);',
'    dispatch(closeMiniCart());',
'  }, [dispatch]);',
'',
'  const openWishlist = useCallback(() => setWishlistOpen(true), []);',
'  const closeWishlist = useCallback(() => setWishlistOpen(false), []);',
'',
'  return {',
'    cartOpen,',
'    wishlistOpen,',
'    quickViewProduct,',
'    handleAddToCart,',
'    handleToggleWishlist,',
'    handleQuickView,',
'    handleOpenCart,',
'    handleCloseCart,',
'    openWishlist,',
'    closeWishlist,',
'    closeQuickView,',
'  };',
'}',
''].join("\n"));

write("features/home/hooks/index.ts", [
'export * from "./useHomeHandlers";',
'export * from "./useWishlistedIds";',
''].join("\n"));

write("features/home/hooks/useWishlistedIds.ts", [
'"use client";',
'import { useMemo } from "react";',
'import { useGetWishlistQuery } from "@/store/api/ecommerce.api";',
'import { useCustomer } from "@/providers/use-customer";',
'import { useAppSelector } from "@/store/hooks";',
'',
'export function useWishlistedIds(): Set<string> {',
'  const customer = useCustomer();',
'  const { data: serverWishlist } = useGetWishlistQuery(undefined, { skip: !customer });',
'  const optimisticIds = useAppSelector((s) => s.wishlistUi.optimisticIds);',
'',
'  return useMemo(() => {',
'    const ids = new Set<string>(serverWishlist?.map((w) => w.productId) ?? []);',
'    for (const id of optimisticIds) {',
'      if (ids.has(id)) ids.delete(id);',
'      else ids.add(id);',
'    }',
'    return ids;',
'  }, [serverWishlist, optimisticIds]);',
'}',
''].join("\n"));

write("features/home/page/EcommerceHomePage.tsx", [
'"use client";',
'import { useAppDispatch, useAppSelector } from "@/store/hooks";',
'import { toggleMobileNav } from "@/store/slices/ui.slice";',
'import { useGetHomePageQuery } from "@/store/api/ecommerce.api";',
'',
'import { Container } from "@/components/primitives/Container";',
'import { ErrorState } from "@/components/shared/ErrorState";',
'',
'import {',
'  SiteHeader,',
'  CategoryNavigation,',
'  SiteFooter,',
'  MobileNavigation,',
'} from "@/features/home/layout";',
'',
'import {',
'  MiniCart,',
'  WishlistDrawer,',
'  QuickViewModal,',
'} from "@/features/home/overlays";',
'',
'import {',
'  HeroSection,',
'  QuickCategorySection,',
'  FlashSaleSection,',
'  PersonalizedSection,',
'  StandardProductSection,',
'  BestSellersSection,',
'  FeaturedCategoriesSection,',
'  BrandShowcaseSection,',
'  DealsSection,',
'  PromotionalBannerSection,',
'  RecentlyViewedSection,',
'  TrustSection,',
'  NewsletterSection,',
'  AppPromotionSection,',
'} from "@/features/home/sections";',
'',
'import { useHomeHandlers } from "@/features/home/hooks/useHomeHandlers";',
'import { useWishlistedIds } from "@/features/home/hooks/useWishlistedIds";',
'',
'export function EcommerceHomePage() {',
'  const dispatch = useAppDispatch();',
'  const { data: home, isLoading, isError, refetch } = useGetHomePageQuery();',
'  const wishlistedIds = useWishlistedIds();',
'  const isMobileNavOpen = useAppSelector((s) => s.ui.isMobileNavOpen);',
'',
'  const {',
'    cartOpen,',
'    wishlistOpen,',
'    quickViewProduct,',
'    handleAddToCart,',
'    handleToggleWishlist,',
'    handleQuickView,',
'    handleOpenCart,',
'    handleCloseCart,',
'    openWishlist,',
'    closeWishlist,',
'    closeQuickView,',
'  } = useHomeHandlers();',
'',
'  const sectionProps = {',
'    onQuickView: handleQuickView,',
'    onAddToCart: handleAddToCart,',
'    onToggleWishlist: handleToggleWishlist,',
'    wishlistedIds,',
'  };',
'',
'  return (',
'    <div className="min-h-dvh bg-[var(--color-background)] text-[var(--color-foreground)]">',
'      <SiteHeader',
'        onOpenCart={handleOpenCart}',
'        onOpenWishlist={openWishlist}',
'        {...sectionProps}',
'      />',
'',
'      <CategoryNavigation />',
'',
'      <main>',
'        {isError && !home ? (',
'          <Container size="wide" className="pt-8">',
'            <ErrorState',
'              title="We couldn\'t load the home page"',
'              description="Please check your connection and try again."',
'              onRetry={refetch}',
'            />',
'          </Container>',
'        ) : (',
'          <>',
'            <HeroSection banners={home?.heroBanners ?? []} isLoading={isLoading} />',
'',
'            <QuickCategorySection',
'              categories={home?.quickCategories ?? []}',
'              isLoading={isLoading}',
'            />',
'',
'            <FlashSaleSection',
'              sale={home?.flashSale}',
'              isLoading={isLoading}',
'              onRetry={refetch}',
'              {...sectionProps}',
'            />',
'',
'            <PersonalizedSection {...sectionProps} />',
'',
'            <StandardProductSection',
'              id="trending"',
'              eyebrow="What\'s hot"',
'              title="Trending Products"',
'              description="The products gaining momentum across Meridian this week."',
'              href="/trending"',
'              products={home?.trending ?? []}',
'              isLoading={isLoading}',
'              isError={isError}',
'              onRetry={refetch}',
'              {...sectionProps}',
'            />',
'',
'            <BestSellersSection',
'              products={home?.bestSellers ?? []}',
'              isLoading={isLoading}',
'              {...sectionProps}',
'            />',
'',
'            <FeaturedCategoriesSection',
'              categories={home?.featuredCategories ?? []}',
'              isLoading={isLoading}',
'            />',
'',
'            <StandardProductSection',
'              id="new-arrivals"',
'              eyebrow="Just landed"',
'              title="New Arrivals"',
'              description="Fresh products from the brands you follow."',
'              href="/new"',
'              variant="featured"',
'              products={home?.newArrivals ?? []}',
'              isLoading={isLoading}',
'              isError={isError}',
'              onRetry={refetch}',
'              {...sectionProps}',
'            />',
'',
'            <BrandShowcaseSection',
'              brands={home?.featuredBrands ?? []}',
'              isLoading={isLoading}',
'            />',
'',
'            <DealsSection deals={home?.deals ?? []} isLoading={isLoading} />',
'',
'            <StandardProductSection',
'              id="top-rated"',
'              eyebrow="Highest rated"',
'              title="Top Rated"',
'              description="Products customers rate highest for quality and value."',
'              href="/top-rated"',
'              products={home?.topRated ?? []}',
'              isLoading={isLoading}',
'              isError={isError}',
'              onRetry={refetch}',
'              {...sectionProps}',
'            />',
'',
'            <RecentlyViewedSection {...sectionProps} />',
'',
'            <PromotionalBannerSection',
'              promotions={home?.promotions ?? []}',
'              isLoading={isLoading}',
'            />',
'',
'            <TrustSection />',
'            <NewsletterSection />',
'            <AppPromotionSection />',
'          </>',
'        )}',
'      </main>',
'',
'      <SiteFooter />',
'',
'      <MiniCart open={cartOpen} onClose={handleCloseCart} />',
'      <WishlistDrawer open={wishlistOpen} onClose={closeWishlist} />',
'      <QuickViewModal',
'        product={quickViewProduct}',
'        onClose={closeQuickView}',
'        onAddToCart={handleAddToCart}',
'      />',
'      <MobileNavigation',
'        open={isMobileNavOpen}',
'        onClose={() => dispatch(toggleMobileNav(false))}',
'      />',
'    </div>',
'  );',
'}',
''].join("\n"));

write("features/home/page/index.ts", [
'export * from "./EcommerceHomePage";',
''].join("\n"));

write("app/layout.tsx", [
'import type { Metadata } from "next";',
'import type { ReactNode } from "react";',
'import "@/styles/globals.css";',
'',
'export const metadata: Metadata = {',
'  title: "Meridian \u2014 Everything you love, delivered",',
'  description:',
'    "Over 1M products from 12,000 verified sellers at prices you can trust.",',
'};',
'',
'export default function RootLayout({ children }: { children: ReactNode }) {',
'  return (',
'    <html lang="en" suppressHydrationWarning>',
'      <body className="bg-[var(--color-background)] text-[var(--color-foreground)] antialiased">',
'        {children}',
'      </body>',
'    </html>',
'  );',
'}',
''].join("\n"));

write("app/page.tsx", [
'import type { Customer } from "@/domain/customer.types";',
'import { Providers } from "@/providers/Providers";',
'import { EcommerceHomePage } from "@/features/home/page/EcommerceHomePage";',
'',
'async function getCustomer(): Promise<Customer | null> {',
'  return null;',
'}',
'',
'export default async function Page() {',
'  const customer = await getCustomer();',
'  return (',
'    <Providers customer={customer}>',
'      <EcommerceHomePage />',
'    </Providers>',
'  );',
'}',
''].join("\n"));

console.log(`\n\x1b[32m\u2705 PR 6 scaffolded (${written} files)\x1b[0m\n`);